### ISSUE TITLE
OpenAPI 3.0

### ISSUE THREAD

**Issue by myroslav** [open-contracting/api-specification#13]
From https://en.wikipedia.org/wiki/OpenAPI_Specification:
> In July 2017, the OpenAPI Initiative [released version 3.0.0](https://www.openapis.org/blog/2017/07/26/the-oai-announces-the-openapi-specification-3-0-0) of its specification.

Should we have Open Contracting API specification also in [OpenAPI 3.0.1 format](https://github.com/OAI/OpenAPI-Specification/blob/master/README.md)?

**Comment by jpmckinney** [comment]
It's not a high priority, but it's a possibility.

**Comment by jpmckinney** [comment]
Closing as additional work on a standard API specification isn't anticipated in the near future, though I agree that specifying this API spec using OpenAPI would follow a good practice (that is not specific to OCDS).
