### ISSUE TITLE
Sketching more detailed API Endpoints

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/api-specification#3]
In [this hackpad](https://hackpad.com/Open-Contracting-Toolbox-API-t4RA7IQHX26) we did some work this week sketching out potential further API methods that might be required by more advanced applications, including search, list and aggregate endpoints.

Opening this issue to keep track of that work.

@yolile was taking forward some of the ideas from this, particularly to be able to drive more visualisations from OCDS data.

**Comment by andrewlorien** [comment]
That’s great, thanks.

Over the next month we’ll be working on an API based on the data available at https://www.tenders.nsw.gov.au/?event=public.advancedsearch.home 

Like the html form, the API will return either a single object or a list of objects based on 8-12 search parameters.  I hadn’t considered pagination until yesterday, and I think we will offer it (we are concerned about server load and the possibility of an unintended DoS - limiting the maximum number of results per page but allowing pagination is a good solution).

 

We are not changing the queries we currently use for the HTML, just adding a view to map the data currently presented as HTML to the OCDS json standard.  And we don’t have pretty URLs.  So our endpoints will be something like ?event=API.Contract.search  and ?event=API.Contract.View, and the fields returned will be exactly the same as the ones currently available in the HTML search (with a few extra elements to comply with the OCDS standard).

 

So.  That’s an invitation from us.  I’ll keep you up to date.

andrew

**Comment by KrzysztofMadejski** [comment]
I'd add to that POST/PUT endpoints to be able to push data from integrated services.

**Comment by tian2992** [comment]
Can you please update the link, as Hackpad was deprecated by Dropbox.

**Comment by jpmckinney** [comment]
Closing, unless Tim has a backup of the hackpad.
