### ISSUE TITLE
rel header for HTML pages for discovery of machine-readable version

### ISSUE THREAD

**Issue by andrewlorien** [open-contracting/api-specification#4]
I just discovered this issue:
https://github.com/open-contracting/standard/issues/183 
I'm for it.  in [NSW eTendering](https://tenders.nsw.gov.au) the first step into open contract publishing is to replicate search and view results in .json.  So we're leapfrogging the common ways that OCDS releases were envisaged, and going straight to a searchable API.  And there should be an exact 1:1 mapping between every possible HTML search result / view page and its .json equivalent.
I hadn't even thought of this in our scoping, but it's easy to implement and an excellent idea.

**Comment by jpmckinney** [comment]
Closing as not strictly an API issue. This idea can however be included in guidance on publishing OCDS data. [Content negotiation](https://www.w3.org/TR/2017/REC-dwbp-20170131/#Conneg) is a related option.
