### ISSUE TITLE
Empty release/record object

### ISSUE THREAD

**Issue by andrewlorien** [open-contracting/api-specification#5]
There are two possible responses to an empty API query (eg a search which returns no results, or a direct query for a release/record that doesn't exist) : 

1. Return the normal root-level objects (publisher, links, etc) with an empty releases array
`{
    "publisher": {
        "uri": "https://tenders.nsw.gov.au",
        "name": "NSW office of Procurement - eTendering"
    },
    "extensions": [
        null,
        "https://tenders.nsw.gov.au/OCDS-extension-schema.json"
    ],
    "releases": [ ],
    "version": "1.0.1",
    "publishedDate": "2017-02-02T05:10:16Z",
    "links": null,
    "license": "https://creativecommons.org/licenses/by/3.0/au/"
}`
2. Just return an error object (our error response is based on the JsonApi spec, which says you either return a data object OR an error object)
`{
    "errors": [
        {
            "detail": "Your query returned no result."
        }
    ]
}`

We're going for option one, because we want to keep the error response for actual errors (it's mapped from our application error handler).  Option 1 doesn't validate against the [OCDS validator](http://standard.open-contracting.org/validator/), but maybe it should.

Anyone want to convince me to do it the other way, or add an official decision to the standard?

**Comment by timgdavies** [comment]
The two cases:

* Search with no results;

vs

* Direct request for release/record that doesn't exist

feel like they could be cases to handle differently. The later might well be an error condition, but the former I agree would be best handled by an empty ```releases``` array.

This looks to be prevented by the ```minItems``` constraint on ```releases``` in the release and record package schemas. I don't see any major reason not to remove this, but tagging @kindly and @Bjwebb in case they can see any problems this would create. 

I've opened an issue over at https://github.com/open-contracting/standard/issues/419 to track this into the schema changes.

**Comment by kindly** [comment]
Sorry for the delay in responding to this.

There is an draft extension for when data is returned via the API

https://github.com/open-contracting/api_extension/

It probably makes more sense for the minItems constraint to be removed in the extension not in the core schema.

**Comment by jpmckinney** [comment]
Closing as resolved through extension.
