### ISSUE TITLE
Programmatic API and HATEOAS

### ISSUE THREAD

**Issue by mpostelnicu** [open-contracting/api-specification#6]
Wondering if Hypermedia as the Engine of Application State (HATEOAS) can be helpful [in this context](https://github.com/open-contracting/api-specification#full-api-type-publishing-a-programmatic-api).

We are using it quite successfully in some of our projects, to automatically generate APIs for accessing/browsing DTOs.

https://en.wikipedia.org/wiki/HATEOAS

This is from  [python-eve](https://github.com/pyeve/eve) documentation:
> Hypermedia as the Engine of Application State (HATEOAS) is enabled by default. Each `GET` response includes a `_links` section. Links provide details on their relation relative to the resource being accessed, and a title. Relations and titles can then be used by clients to dynamically updated their UI, or to navigate the API without knowing its structure beforehand. An example:

```
{
    "_links": {
        "self": {
            "href": "people",
            "title": "people"
        },
        "parent": {
            "href": "/",
            "title": "home"
        },
        "next": {
            "href": "people?page=2",
            "title": "next page"
        },
        "last": {
            "href": "people?page=10",
            "title": "last page"
        }
    }
}
```
>A `GET` request to the API home page (the API entry point) will be served with a list of links to accessible resources. From there, any client could navigate the API just by following the links provided with every response.
>HATEOAS links are always relative to the API entry point, so if your API home is at `examples.com/api/v1`, the self link in the above example would mean that the people endpoint is located at `examples.com/api/v1/people`.

### Tools

Python 
http://ripozo.readthedocs.io/en/latest/
http://python-eve.org/features.html#hateoas

Spring/Java
http://projects.spring.io/spring-hateoas/

**Comment by KrzysztofMadejski** [comment]
We've been using eve with hateoas support in http://api.parldata.eu/. Can only recommend it.

**Comment by akuckartz** [comment]
Please support JSON-LD for this purpose. See also http://www.hydra-cg.com/

**Comment by jpmckinney** [comment]
Closing as additional work on a standard API specification isn't anticipated in the near future, though I agree that HATEOS is a good practice (and not specific to OCDS).
