### ISSUE TITLE
Summary  info

### ISSUE THREAD

**Issue by yshalenyk** [open-contracting/api-specification#9]
I think api should provide ability to retrieve summary info about all available data. Example case: end user would like to know list of extensions available in data.
Example of response:

```
{
    "releases": {
          "total": "12"
    },
    "records": {
          "total": "4",
    },
    "extensions": [
          "https://raw.githubusercontent.com/open-contracting/ocds_finance_extension/master/extension.json",
          "https://raw.githubusercontent.com/open-contracting/ocds_lots_extension/master/extension.json"
    ]
}
```

**Comment by mireille-raad** [comment]
In the spirit of issue https://github.com/open-contracting/api-specification/issues/10 that you just raised, it would be useful to add a building block that flags the last updated date time for the data at each of the stages of the procurement process... or the last ocid.

**Comment by jpmckinney** [comment]
Closing as additional work on a standard API specification isn't anticipated in the near future, though I agree that providing summary information about a dataset through its API is a good practice (and not specific to OCDS).
